import React from 'react';
import { Box, Container, Typography, Divider, alpha } from '@mui/material';
import { ArrowBack } from '@mui/icons-material';
import { useNavigate } from 'react-router-dom';
import { Button } from '@mui/material';

const NAVY = '#1e3a8a';
const TEAL = '#0d9488';
const SLATE_900 = '#0f172a';
const SLATE_500 = '#64748b';
const SLATE_400 = '#94a3b8';
const SLATE_200 = '#e2e8f0';
const BG = '#f8fafc';

const FAQ = () => {
  const navigate = useNavigate();

  const faqs = [
    {
      question: 'Is the equity split calculated by your platform legally binding?',
      answer: 'The equity split calculations provided by Guild Space are recommendations based on the information you provide through our questionnaire. The generated Co-Founder Agreement documents are templates that should be reviewed by a qualified attorney before signing. We recommend consulting with legal counsel to ensure the agreement meets your specific needs and complies with local laws.',
    },
    {
      question: 'Can I use Guild Space with someone I already know?',
      answer: 'Yes! Guild Space works for both finding new co-founders and formalizing partnerships with people you already know. You can invite an existing co-founder to join your workspace, complete the equity questionnaire together, and use our tools to track KPIs, make decisions, and manage your partnership.',
    },
    {
      question: 'How is my data protected?',
      answer: 'We take data security seriously. All data is encrypted in transit and at rest. We use industry-standard security practices and only share information within your workspace with authorized members. We never sell your personal information. For more details, please review our Privacy Policy.',
    },
    {
      question: 'What happens if we dissolve the partnership?',
      answer: 'The Co-Founder Agreement templates generated by Guild Space include provisions for vesting schedules and what happens to equity if a founder leaves. However, the specific terms depend on the agreement you sign. We recommend working with a lawyer to customize these terms based on your situation. Your workspace data remains accessible to all members unless you choose to delete it.',
    },
    {
      question: 'How does the matching algorithm work?',
      answer: 'Our matching system considers multiple factors including skills, project stage, location preferences, working style, commitment level, and funding approach. You can see your compatibility score with each potential co-founder. The algorithm prioritizes matches where both founders have expressed interest in each other\'s projects.',
    },
    {
      question: 'Do I need to pay to find a co-founder?',
      answer: 'No! Our Free tier allows you to create one workspace and swipe through 10 profiles per month. This is enough to get started and find potential matches. Pro and Pro+ plans offer unlimited discovery, advanced equity tools, and additional features for teams ready to scale.',
    },
    {
      question: 'Can I use Guild Space if I already have a co-founder?',
      answer: 'Absolutely. Many teams use Guild Space to structure their existing partnership, formalize equity splits, track KPIs, and maintain accountability. You can skip the discovery phase and go straight to setting up your workspace.',
    },
    {
      question: 'How do advisors earn equity?',
      answer: 'Advisors join workspaces and provide guidance to founders. The equity allocation for advisors is typically 1-3% and is determined by the founders when setting up their equity structure. Advisors must pay a one-time onboarding fee ($69) and annual renewal ($39/year) to maintain their profile and receive project requests.',
    },
    {
      question: 'What if I disagree with the calculated equity split?',
      answer: 'The equity calculator provides AI-recommended splits based on your inputs, but you\'re not locked into them. You can create custom split scenarios, adjust percentages manually, and discuss different options with your co-founder. The goal is to help you have informed conversations, not to dictate the final split.',
    },
    {
      question: 'Can I export my data?',
      answer: 'Yes, you can download documents (agreements, decisions, etc.) from your workspace at any time. For other data exports, please contact our support team. We believe you should have full control over your information.',
    },
    {
      question: 'What makes Guild Space different from other co-founder matching platforms?',
      answer: 'Guild Space goes beyond matching—we provide a complete workspace OS for partnerships. After matching, you get tools for equity agreements, KPI tracking, task management, decision logging, and weekly check-ins. Everything you need to build and scale together is in one place, not scattered across different tools.',
    },
    {
      question: 'Is there a mobile app?',
      answer: 'Guild Space is currently a web application optimized for mobile browsers. You can access it from any device with a modern browser. We\'re working on native mobile apps for iOS and Android—stay tuned!',
    },
  ];

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: BG, py: { xs: 4, md: 6 } }}>
      <Container maxWidth="md">
        {/* Header */}
        <Box sx={{ mb: 4 }}>
          <Button
            startIcon={<ArrowBack />}
            onClick={() => navigate(-1)}
            sx={{
              mb: 3,
              color: SLATE_500,
              textTransform: 'none',
              '&:hover': { color: TEAL, bgcolor: 'transparent' },
            }}
          >
            Back
          </Button>
          <Typography variant="h3" sx={{ fontWeight: 800, color: SLATE_900, mb: 2, fontSize: { xs: '2rem', md: '2.5rem' } }}>
            Frequently Asked Questions
          </Typography>
          <Typography variant="body1" sx={{ color: SLATE_500, lineHeight: 1.8 }}>
            Find answers to common questions about Guild Space, equity splits, partnerships, and more.
          </Typography>
        </Box>

        {/* FAQ Items */}
        {faqs.map((faq, index) => (
          <Box key={index} sx={{ mb: 4 }}>
            <Typography variant="h5" sx={{ fontWeight: 700, color: SLATE_900, mb: 1.5, fontSize: '1.15rem' }}>
              {faq.question}
            </Typography>
            <Typography
              variant="body2"
              sx={{
                color: SLATE_500,
                lineHeight: 1.8,
                fontSize: '0.95rem',
              }}
            >
              {faq.answer}
            </Typography>
            {index < faqs.length - 1 && <Divider sx={{ mt: 3, borderColor: SLATE_200 }} />}
          </Box>
        ))}

        {/* Contact note */}
        <Box sx={{
          mt: 6, p: 3, borderRadius: 2,
          bgcolor: alpha(TEAL, 0.05), border: '1px solid', borderColor: alpha(TEAL, 0.2),
        }}>
          <Typography variant="body2" sx={{ color: SLATE_500, lineHeight: 1.8, mb: 1 }}>
            <strong>Still have questions?</strong>
          </Typography>
          <Typography variant="body2" sx={{ color: SLATE_500, lineHeight: 1.8 }}>
            If you can't find the answer you're looking for, feel free to reach out through our feedback system (available when signed in) or contact us directly. We're here to help!
          </Typography>
        </Box>
      </Container>
    </Box>
  );
};

export default FAQ;
